//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class IMPRUMUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPRUMUT()
        {
            this.Review = new HashSet<REVIEW>();
        }
        [DataMember]
        public int ImprumutId { get; set; }
        [DataMember]
        public int CarteId { get; set; }
        [DataMember]
        public int CititorId { get; set; }
        [DataMember]
        public System.DateTime DataImprumut { get; set; }
        [DataMember]
        public System.DateTime DataScadenta { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DataRestituire { get; set; }
       
        public virtual CARTE Carti { get; set; }
     
        public virtual CITITOR Cititor { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> Review { get; set; }
    }
}
