//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    [DataContract]
    public partial class REVIEW
    {
        [DataMember]
        public int ReviewId { get; set; }
        [DataMember]
        public string Text { get; set; }
        [DataMember]
        public int ImprumutId { get; set; }
        [DataMember]
        public virtual IMPRUMUT Imprumut { get; set; }
    }
}
