//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWcf.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AchizitieCarte", Namespace="http://schemas.datacontract.org/2004/07/Domain.ModelAux")]
    [System.SerializableAttribute()]
    public partial class AchizitieCarte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumarCartiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenumeAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitluField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere {
            get {
                return this.DescriereField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriereField, value) != true)) {
                    this.DescriereField = value;
                    this.RaisePropertyChanged("Descriere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumarCarti {
            get {
                return this.NumarCartiField;
            }
            set {
                if ((this.NumarCartiField.Equals(value) != true)) {
                    this.NumarCartiField = value;
                    this.RaisePropertyChanged("NumarCarti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeAutor {
            get {
                return this.NumeAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeAutorField, value) != true)) {
                    this.NumeAutorField = value;
                    this.RaisePropertyChanged("NumeAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrenumeAutor {
            get {
                return this.PrenumeAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenumeAutorField, value) != true)) {
                    this.PrenumeAutorField = value;
                    this.RaisePropertyChanged("PrenumeAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu {
            get {
                return this.TitluField;
            }
            set {
                if ((object.ReferenceEquals(this.TitluField, value) != true)) {
                    this.TitluField = value;
                    this.RaisePropertyChanged("Titlu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBiblioWcf")]
    public interface IBiblioWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioWcf/CumparaCarte", ReplyAction="http://tempuri.org/IBiblioWcf/CumparaCarteResponse")]
        bool CumparaCarte(TestWcf.ServiceReference1.AchizitieCarte carte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBiblioWcf/CumparaCarte", ReplyAction="http://tempuri.org/IBiblioWcf/CumparaCarteResponse")]
        System.Threading.Tasks.Task<bool> CumparaCarteAsync(TestWcf.ServiceReference1.AchizitieCarte carte);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBiblioWcfChannel : TestWcf.ServiceReference1.IBiblioWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiblioWcfClient : System.ServiceModel.ClientBase<TestWcf.ServiceReference1.IBiblioWcf>, TestWcf.ServiceReference1.IBiblioWcf {
        
        public BiblioWcfClient() {
        }
        
        public BiblioWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiblioWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiblioWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiblioWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CumparaCarte(TestWcf.ServiceReference1.AchizitieCarte carte) {
            return base.Channel.CumparaCarte(carte);
        }
        
        public System.Threading.Tasks.Task<bool> CumparaCarteAsync(TestWcf.ServiceReference1.AchizitieCarte carte) {
            return base.Channel.CumparaCarteAsync(carte);
        }
    }
}
